config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :follow, :follower] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, length: {maximum: 200,minimum: 1}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships, foreign_key: 'user_id'
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id',dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user
  
   def following?(other_user)
    self.followings.include?(other_user)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end 
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end 
  

  validates :name, length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!,except: [:top, :about]


      def after_sign_in_path_for(resource)
      user_path(resource)
      end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        redirect_to book_path(@book), notice: 'You have created book successfully.'
      else
        @user = current_user
        @books = Book.all
        render :index
      end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def show
    @book_find = Book.find(params[:id])
    @user = @book_find.user
    @book = Book.new
    @users = User.all
    @book_comment = BookComment.new
  end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
   else
      render :edit
   end
 end

  private

    def book_params
    params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
    
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
   before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user_path(@user)
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user_path(@user)
    end
  end

  private

  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book=Book.new
    @user = current_user
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all

  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
    <h2>New book</h2>
    <%= form_with model:book, local:true do |f| %>
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control form-group"%>
      <label for= "book_body">Opinion</label>
      <%= f.text_area :body, class: "form-control form-group" %>
      <%= f.submit 'Create Book', class: "btn btn-success"  %>
        
    <% end %>

app/views/books/edit.html.erb
book.edit
<p id="notice"></p>
<div class="container">

     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-5 mx-auto">
      <h2>Editing Book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <p><label for="inputName">Title</label></p>
        <p><%= f.text_field :title, class:"form-control form-group",autofocus: true, id:"inputTitle", placeholder:"タイトル" %></p>
        <p><label for="inputOpinion">Opinion</label></p>
        <p><%= f.text_field :body, class:"form-control form-group",autofocus: true, id:"inputBody", placeholder:"Opinion" %></p>
      <%= f.submit "Update Book", class:"btn" %></br>
      <% end %>
      <p></p>
      <span><%= link_to "Show", book_path(@book), class: 'btn btn-sm btn-success' %></span>
      <span>|</span>
      <span><%= link_to "Back", books_path, class: 'btn btn-sm btn-success' %></span>
    </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  <div id="error_explanation">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: current_user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
      <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title ,book_path(book) %></td>
                <td><%= book.body %></td>
                <td>
                  <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      ♥<%= book.favorites.count %>
                  <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      ♡<%= book.favorites.count %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %></td>
              </tr>
      <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  <div id="error_explanation">
     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: @user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @book_find.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                  <% end %>
                  <br><%= link_to @user.name, user_path(@user) %></br>
                </td>
                <td><%= link_to @book_find.title, book_path(@book_find.id) %></td>
                <td><%= @book_find.body %></td>
                <td><% if @book_find.favorited_by?(current_user) %>
                      <%= link_to book_favorites_path(@book_find), method: :delete do %>
                        ♥<%= @book_find.favorites.count %>
                      <% end %>
                    <% else %>
                      <%= link_to book_favorites_path(@book_find), method: :post do %>
                        ♡<%= @book_find.favorites.count %>
                    　<% end %>
                  　<% end %>
                </td>
                <td>コメント件数:<%= @book_find.book_comments.count %></td>
                <% if @user.id == current_user.id %>
                  <td><%= link_to "Edit", edit_book_path(@book_find.id) %></td>
                  <td><%= link_to "Destroy", book_path(@book_find.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
　　　　　<h4><strong>コメント</strong></h4>
          <table class="table table-hover table-inverse">
            <tbody>
                  <% @book_find.book_comments.each do |book_comment| %>
                  <tr>
                   <td>
                    <%= link_to user_path(@user.id) do %>
                    <%= attachment_image_tag book_comment.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                    <% end %>
                    <br><%= link_to book_comment.user.name, user_path(@user) %></br>
                  </td>
                  <td>
                    <%= book_comment.comment %>
                  </td>
                  <td>
                    <% if book_comment.user == current_user %>
                    <div class="comment_delete">
                      <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
                    </div>
                    <% end %>
                  </td>
                </tr>
                  <% end %>
               </tbody>
              </table>
              <%= form_with(model:[@book_find, @book_comment], local: true) do |f| %>
              <table class=="table table-hover table-inverse">
                <tbody>
                  <tr>
                    <%= f.text_area :comment, rows: '5',placeholder: "コメントをここに" %>
                    <%= f.submit "送信" %>
                  </tr>
                </tbody>
              </table>
              <% end %>
      </div>
    </div>
  </div>

app/views/homes/about.html.erb
<div class="about">
 <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>

app/views/homes/top.html.erb
<%= render 'layouts/notifications' %>
 <div class="outer">
  <div class="inner">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      </div>
      </br>
      <div class="login">
        <%= link_to "Log In", new_user_session_path, class: 'nav-link text-white' %>
      </div>
      <div class="signup">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-white' %>
      </div>
 </div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white pt-1 pb-1">
      <nav class="navbar navbar-expand-lg navbar-light navbar-white">
        <div class="container">
          <h2><%= link_to "Bookers", root_path, class: 'text-white'%></h2>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li>
              <i class="fas fa-home"></i><%= link_to 'Home', user_path(id: current_user), class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
             <i class="fas fa-users"></i><%= link_to 'Users', users_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
             <li>
              <i class="fas fa-book-open"></i><%= link_to 'Books', books_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
              <i class="fas fa-sign-out-alt"></i><%= link_to "logout", destroy_user_session_path, method: :delete, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <% else %>
             <li>
               <i class="fas fa-home" ></i><%= link_to 'Home', root_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
             <li>
              <i class="fas fa-link" ></i><%= link_to 'About', home_about_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
              <i class="fas fa-user-plus"></i><%= link_to "sign up", new_user_registration_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
              <i class="fas fa-sign-in-alt"></i><%= link_to "login", new_user_session_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
  <h2>User info</h2>
   <p><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
   <table class="table">
       <tbody>
           <tr>
               <th>name</th>
               <th class="profile-name"><%= user.name %></th>
            </tr>
            <tr>
               <th>introduction</th>
               <td><%= user.introduction %></td>
            </tr>
            <tr>
                <th>Follows</th>
                <td><%= link_to @user.followings.count, followings_user_path(@user.id) %></td>
            </tr>
            <tr>
                <th>Followers</th>
                <td><%= link_to @user.followers.count, followers_user_path(@user.id) %></td>
            </tr>
            <tr>
                <th></th>
                <td>
                 <% unless current_user == user %>
                   <% if current_user.following?(user) %>
                     <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
                     <% end %>
                  <% else %>
                    <%= form_for(current_user.relationships.build) do |f| %>
                      <%= hidden_field_tag :follow_id, user.id %>
                      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
                     <% end %>
                  <% end %>
                <% end %>
               </td>
            </tr>
        </tbody>
    </table>
  <div class="row">
    <%= link_to '', edit_user_path(user), class: "fas fa-user-cog btn-i-edit btn-outline-secondary btn-block" %>
  </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div id="error_explanation">
     <% if @user.errors.any? %>
    <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @user.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-5 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <p><label for="inputName">Name</label></p>
      <p><%= f.text_field :name,class:"form-control form-group", autofocus: true, id:"inputName", placeholder:"名前" %></p>
      <p><label for="inputImage">Image</label></P>
      <p><%= f.attachment_field :profile_image, class:"input-profile-image" %></p>
      <p><label for="inputIntroduction">introduction</label></p>
      <p><%= f.text_field :introduction,class:"form-control form-group", autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文" %></p>
      <%= f.submit "Update User", class:"btn-edit" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<div class="container px5 px-sm-0">
    <div class="row">
        <div class="col-md-12 offset-md-1">
          <p></p>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.followings.count %></td>
                  <td>フォロワー数:<%= user.followers.count %></td>
                  <td><%= link_to "Show", user_path(user) %></td>
                 </tr>
                <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/followings.html.erb
<h2>Follow Users</h2>
<div class="container px5 px-sm-0">
    <div class="row">
        <div class="col-md-12 offset-md-1">
          <p></p>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.followings.count %></td>
                  <td>フォロワー数:<%= user.followers.count %></td>
                  <td><%= link_to "Show", user_path(user) %></td>
                </tr>
                <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  　<div id="error_explanation">
   <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: current_user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Users</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
      <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user) %></td>
                   <td>
                 <% unless current_user == user %>
                   <% if current_user.following?(user) %>
                     <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
                     <% end %>
                  <% else %>
                    <%= form_for(current_user.relationships.build) do |f| %>
                      <%= hidden_field_tag :follow_id, user.id %>
                      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
                     <% end %>
                  <% end %>
                <% end %>
               </td>
              </tr>
      <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  <div id="error_explanation">
     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: @user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
      <% @books.each do |books| %>
              <tr>
                <td>
                  <%= link_to user_path(books.user) do %>
                    <%= attachment_image_tag books.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%=link_to books.title, book_path(books) %></td>
                <td><%= books.body %></td>
                <td><%= link_to "コメント数:#{books.book_comments.count}", book_path(books.id) %></td>
              </tr>
      <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>